### ISSUE TITLE
Plottable.js 1.0 broken for online examples : undefined is not a function (chrome) Object doesn't support this action (IE)

### ISSUE THREAD

**Issue by regeter** [palantir/plottable-website#100]
Examples use 
Plottable 0.54.0

The latest on website is 
Plottable 1.0.0-rc1

With 1.0 the examples do not work. I am getting error
undefined is not a function (chrome) 
Object doesn't support this action (IE)

I blamed my WebForms for doing something funny with the scripts, but as soon as I used 0.54 all the online examples worked great. Can we update them? Is there a new documentation out there?

**Comment by jtlan** [comment]
Hi @regeter,

The release candidates (`1.0.0-rc1`, etc) are intended to allow for pre-integration testing before the release of `1.0.0`, rather than actual production use. We're planning to upgrade the examples on the website once `1.0.0` is released. 

However, if you're interested in trying out the release candidates, we have an [upgrade guide](https://github.com/palantir/plottable/wiki/Upgrading-to-1.0.0) for converting to the `1.0.0` API. Please let us know how they work out for you, and if you encounter any problems. Thanks!

**Comment by rcchen** [comment]
These are fixed as of the 1.0.0 release (#101). Closing.
